### ISSUE TITLE
Add duration as manual override

### ISSUE THREAD

**Issue by NikitaRubocki** [toureholder/flutter_adaptive_layout#4]
I love that animations are included in this package, but I want the ability to override the duration.  Based on the internal files, I can see that duration is set to 1.  It would be nice if this variable could be pulled out and set by the developer, similar to how flutter animations works with most everything else.  Otherwise, to get the right animation time, I have to go and build an entire custom animation, when all I really want to do is shorten the animation with some of the given presets.

<img width="588" alt="CleanShot 2023-08-28 at 21 38 19@2x" src="https://github.com/toureholder/flutter_adaptive_layout/assets/37080484/606bf662-44d3-4c5c-ba2f-def171af4572">

**Comment by toureholder** [comment]
Hi @NikitaRubocki! Could you point me to where duration is set to 1 in this package's source code? Thanks for reaching out!

**Comment by NikitaRubocki** [comment]
Hey @toureholder, thanks for the quick response! It's in the `adaptive_layout.dart` file, on line 216 in the `_AdaptiveLayoutState` class.

**Comment by toureholder** [comment]
Sorry, but the code you are referring to is not part of [adaptive_layout.dart](https://github.com/toureholder/flutter_adaptive_layout/blob/main/lib/src/adaptive_layout.dart).
